services:
  blazorappsecure:
    image: ${DOCKER_REGISTRY-}blazorappsecure
    container_name: blazorappsecure
    build:
      context: .
      dockerfile: BlazorAppSecure/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"
  blazorappsecure.database:
    image: postgres:latest
    container_name: blazorappsecure.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blazorappsecure
    volumes:
      - ./.containers/blazorappsecure.database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - blazorappsecure.database