@WebApiAuth_HostAddress = https://localhost:7178

GET {{WebApiAuth_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebApiAuth_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "Username" : "user123",
  "Password" : "Pass123!"
}

###

POST {{WebApiAuth_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "Username" : "raul",
  "Password" : "Pass123!",
  "roles":["admin"]
}

###

POST {{WebApiAuth_HostAddress}}/api/auth/addrole
Content-Type: application/json

{
  "RoleName": "benef"
}

###

POST {{WebApiAuth_HostAddress}}/api/auth/assignrole
Content-Type: application/json

{
  "username": "rs98",
  "rolename": "benef"
}

###

POST {{WebApiAuth_HostAddress}}/api/auth/assignroles
Content-Type: application/json

{
  "username":"raul",
  "rolenames":[
    "admin","benef","tecnico"
  ]
}

###
