@identitywebapiauthentication_HostAddress = https://localhost:7268

GET {{identitywebapiauthentication_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{identitywebapiauthentication_HostAddress}}/api/user
Authorization: Bearer 
###

@emailId=raul@gmail.com
@apiKey = Bearer 
GET {{identitywebapiauthentication_HostAddress}}/api/role/GetUserRoles?emailId={{emailId}}
Authorization: {{apiKey}}

###
