@identitywebapiauthentication_HostAddress = https://localhost:7268

GET {{identitywebapiauthentication_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{identitywebapiauthentication_HostAddress}}/api/user
Authorization: Bearer CfDJ8Op3HKqz1kREqC8n90c3bEKyAyr2t3SJDNn8Ts5ConvA-gf4soHLDVeNhzUdRuyM2a-9KrR8NTJ_mw0nlibGeXxnJqjD3z5YlGOPr56TnUvsiPOs57nrqk8hW09IfKEGnRAg4klQFrOI77NdHO7Y1OHOc040Gru6UMB9T57iEmS5XTi-K2JU9zP6YFwrfFj-MgKSdZArh5NH04EtGPJ2iWLxKfp5gGcBcKS_saIuEtDyUJ8LV8nqAeY6Ky29dHemcKJjHo7JIvjh8H3XkmXG3_dgm69PG0fJNmap8ZIFkwMyvb3Im8lPTFGqHLzPPOF70FvHxMyFrrd5SvRM6MfBOHXKr0OJlh2RZvDXByij6A94VRla6nlw2PZnRwsJbeRuAirzfS1c0zaUY-ro0p3ZV8j95QU3ctjpwIMrwO3OlikD4kl8_tFQGfAMsebCkqQUfUjG1ohBpaEbt7VReDDMWuX3aCJpaTKlrQO3blZOKcANXW7d8hXyCtl6yI75aj2zofbZBqrxAZwIXcmnXlwqJjQ5tzddvGpk3xwxh2QueM89Cu6iM3gkJHVI8LBR7nCh29SpUKRU_dkrlv2X0U05gw42c6n6wNHH24v805YHp1e6_73JhF9nVhL3WnfpeXUHjqzuhQrwzHN1lfcSJpnF4jMzAl5ZHcawSUWsR9heX0btHidesKumim45kB8D36-oVg
###
